[pytest]
filterwarnings =
    ignore:__array__ implementation doesn't accept a copy keyword.*:DeprecationWarning:vortexfitting\..*
    ignore:Consolidated metadata is currently not part in the Zarr format 3 specification.*:UserWarning
